version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/app.dockerfile
    container_name: api_container
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres_db
    networks:
      - learning

  postgres_db:
    build:
      context: .
      dockerfile: ./docker/db.dockerfile
    container_name: postgres_db_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "1234:5432"
    volumes:
      - ./database_postgres:/var/lib/postgresql/dat
    networks:
      - learning
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres_db
    ports:
      - "5050:80"
    restart: unless-stopped
    networks:
      - learning

volumes:
  database_postgres:
# Networks to be created to facilitate communication between containers
networks:
  learning:
    driver: bridge
